# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SLPWalletTestApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SLPWalletTestApp
  pod 'SLPWallet', :git => 'https://github.com/bitcoin-portal/slp-wallet-sdk-ios.git', :branch => 'master'


  target 'SLPWalletTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SLPWalletTestAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
