language: objective-c
osx_image: xcode10.1
before_install:
  - travis_retry pod repo update
install:
  - gem install cocoapods --pre
  - pod deintegrate
  - pod cache clean --all
  - pod setup
  - travis_wait 30 pod install
script:
  - xcodebuild -workspace SLPWallet.xcworkspace -scheme SLPWallet -destination platform\=iOS\ Simulator,OS\=12.1,name\=iPhone\ XR -enableCodeCoverage YES test > /dev/null
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'SLPWallet' -t 256b3c8f-ae5a-4958-85b5-d5bbc86ebb83 > /dev/null